const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    designation: "Manager",
    access: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    designation: "Developer",
    access: "Inactive",
  },
  {
    id: 3,
    name: "Sam Johnson",
    email: "sam@example.com",
    phone: "555-555-5555",
    designation: "Designer",
    access: "Active",
  },
  {
    id: 4,
    name: "Sara Connor",
    email: "sara@example.com",
    phone: "333-333-3333",
    designation: "Developer",
    access: "Inactive",
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael@example.com",
    phone: "444-444-4444",
    designation: "Tester",
    access: "Active",
  },
  {
    id: 6,
    name: "Emily Davis",
    email: "emily@example.com",
    phone: "555-666-7777",
    designation: "Manager",
    access: "Inactive",
  },
  {
    id: 7,
    name: "David Wilson",
    email: "david@example.com",
    phone: "888-999-0000",
    designation: "Developer",
    access: "Active",
  },
  {
    id: 8,
    name: "Laura Taylor",
    email: "laura@example.com",
    phone: "111-222-3333",
    designation: "Designer",
    access: "Inactive",
  },
  {
    id: 9,
    name: "James Moore",
    email: "james@example.com",
    phone: "444-555-6666",
    designation: "Tester",
    access: "Active",
  },
  {
    id: 10,
    name: "Linda Anderson",
    email: "linda@example.com",
    phone: "777-888-9999",
    designation: "Manager",
    access: "Inactive",
  },
  {
    id: 11,
    name: "Robert Thomas",
    email: "robert@example.com",
    phone: "000-111-2222",
    designation: "Developer",
    access: "Active",
  },
  {
    id: 12,
    name: "Barbara Jackson",
    email: "barbara@example.com",
    phone: "333-444-5555",
    designation: "Designer",
    access: "Inactive",
  },
  {
    id: 13,
    name: "William White",
    email: "william@example.com",
    phone: "666-777-8888",
    designation: "Tester",
    access: "Active",
  },
  {
    id: 14,
    name: "Elizabeth Harris",
    email: "elizabeth@example.com",
    phone: "999-000-1111",
    designation: "Manager",
    access: "Inactive",
  },
  {
    id: 15,
    name: "Joseph Martin",
    email: "joseph@example.com",
    phone: "222-333-4444",
    designation: "Developer",
    access: "Active",
  },
  {
    id: 16,
    name: "Mary Thompson",
    email: "mary@example.com",
    phone: "555-666-7777",
    designation: "Designer",
    access: "Inactive",
  },
  {
    id: 17,
    name: "Charles Garcia",
    email: "charles@example.com",
    phone: "888-999-0000",
    designation: "Tester",
    access: "Active",
  },
  {
    id: 18,
    name: "Patricia Martinez",
    email: "patricia@example.com",
    phone: "111-222-3333",
    designation: "Manager",
    access: "Inactive",
  },
  {
    id: 19,
    name: "Christopher Robinson",
    email: "christopher@example.com",
    phone: "444-555-6666",
    designation: "Developer",
    access: "Active",
  },
  {
    id: 20,
    name: "Jennifer Clark",
    email: "jennifer@example.com",
    phone: "777-888-9999",
    designation: "Designer",
    access: "Inactive",
  },
];

export default users;
